#!/bin/bash

help() {
    cat <<HELPEOF
Unlock OPAL drives by prompting for password
HELPEOF
}

build() {
    add_binary /usr/bin/sedutil-cli
    add_binary /usr/bin/clear
    add_binary /usr/bin/find
    add_binary /usr/bin/gawk
    add_binary /usr/bin/grep
    add_binary /usr/bin/readlink
    add_binary /usr/bin/stty
    add_binary /usr/bin/xargs
    add_binary /usr/sbin/partprobe

    add_runscript
}